version: "3.8"

services:
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
      MYSQL_DATABASE: "test"
    ports:
      - "3306:3306"
    expose:
      - "3306"
